(function() {
'use strict';

// ============================================================
// Level 1: The Blighted Village - Room-based design
// 8 rooms, each ~960px wide. Canvas: 960x400
// wallThick=28, main floor at room.y + room.h - 28
// Collision generated by Room.generateCollision()
// ============================================================

var R1 = 0, R2 = 960, R3 = 1920, R4 = 2880, R5 = 3840, R6 = 4800, R7 = 5760, R8 = 6720;

W.StoryLevel1 = {
    name: 'The Blighted Village',
    width: 7680,
    bgTheme: 'village',
    storyText: "Villagers report monster attacks worse than ever. A strange medallion was found on a dead nekker...",
    platforms: [],
    rooms: [
        // ==============================
        // ROOM 1: Alley Entrance (0-960)
        // Main floor at y:372. One interior shelf floor for climbing.
        // ==============================
        {x:R1, y:60, w:960, h:340, theme:'village',
            noCeiling: false,
            floors: [
                {y:240, w:400, h:20}       // upper shelf at abs y:300
            ],
            doors: [{side:'right', offset:200, size:140}],
            features: [
                {type:'torch', x:100, y:120},
                {type:'torch', x:800, y:120},
                {type:'cobweb', x:28, y:80}
            ]},

        // ==============================
        // ROOM 2: House Interior (960-1920)
        // Two-story house. Interior floor for 2nd level.
        // ==============================
        {x:R2, y:60, w:960, h:340, theme:'village',
            noCeiling: false,
            floors: [
                {y:180, w:904, h:20}        // 2nd floor at abs y:240 (full width minus walls)
            ],
            doors: [
                {side:'left', offset:200, size:140},
                {side:'right', offset:200, size:140}
            ],
            features: [
                {type:'torch', x:100, y:100},
                {type:'torch', x:800, y:100},
                {type:'shelf', x:200, y:130, w:60},
                {type:'window', x:460, y:90, w:24, h:36}
            ]},

        // ==============================
        // ROOM 3: Courtyard (1920-2880)
        // Semi-open (no ceiling), one interior balcony floor.
        // ==============================
        {x:R3, y:60, w:960, h:340, theme:'village',
            noCeiling: true,
            floors: [
                {y:260, w:250, h:20, x:620},  // low step right (abs y:320) — reachable from main floor (52px gap)
                {y:180, w:400, h:20, x:28},    // balcony left (abs y:240) — reachable from low step (80px gap)
                {y:100, w:300, h:20, x:560}    // upper balcony right (abs y:160) — reachable from balcony (80px gap)
            ],
            doors: [
                {side:'left', offset:200, size:140},
                {side:'right', offset:200, size:140}
            ],
            features: [
                {type:'torch', x:150, y:160},
                {type:'torch', x:750, y:160}
            ]},

        // ==============================
        // ROOM 4: Church Interior (2880-3840)
        // Tall room, noCeiling, 2 interior floors for climbing.
        // ==============================
        {x:R4, y:20, w:960, h:380, theme:'village',
            noCeiling: true,
            floors: [
                {y:310, w:300, h:20, x:580},  // low step right (abs y:330) — reachable from main floor at 372
                {y:220, w:904, h:20},          // mid floor at abs y:240 — reachable from low step (90px gap)
                {y:150, w:350, h:20, x:28},   // zigzag left (abs y:170) — reachable from mid floor (70px gap)
                {y:120, w:600, h:20, x:180},  // choir loft at abs y:140 — reachable from zigzag left (30px gap)
                {y:50, w:280, h:20, x:600}    // bell tower ledge right (abs y:70) — reachable from choir loft (70px gap)
            ],
            doors: [
                {side:'left', offset:240, size:140},
                {side:'right', offset:240, size:140}
            ],
            features: [
                {type:'torch', x:100, y:160},
                {type:'torch', x:800, y:160},
                {type:'banner', x:460, y:60, color:'#6a1a1a'},
                {type:'window', x:440, y:40, w:28, h:50}
            ]},

        // ==============================
        // ROOM 5: Market Cellar (3840-4800)
        // Underground feel: lower y, smaller h. One shelf floor.
        // ==============================
        {x:R5, y:100, w:960, h:300, theme:'village',
            noCeiling: false,
            floors: [
                {y:160, w:700, h:20}        // shelf at abs y:260
            ],
            doors: [
                {side:'left', offset:160, size:140},
                {side:'right', offset:160, size:140}
            ],
            features: [
                {type:'torch', x:100, y:120},
                {type:'torch', x:800, y:120},
                {type:'cobweb', x:28, y:120},
                {type:'shelf', x:300, y:110, w:50}
            ]},

        // ==============================
        // ROOM 6: Damaged Building (4800-5760)
        // Standard height, one upper floor level.
        // ==============================
        {x:R6, y:60, w:960, h:340, theme:'village',
            noCeiling: false,
            floors: [
                {y:180, w:800, h:20}        // upper floor at abs y:240
            ],
            doors: [
                {side:'left', offset:200, size:140},
                {side:'right', offset:200, size:140}
            ],
            features: [
                {type:'torch', x:120, y:130},
                {type:'torch', x:780, y:130},
                {type:'cobweb', x:860, y:80}
            ]},

        // ==============================
        // ROOM 7: Nekker Nest (5760-6720)
        // Cave room: lower y, smaller h. One rock shelf.
        // ==============================
        {x:R7, y:100, w:960, h:300, theme:'village',
            noCeiling: false,
            floors: [
                {y:230, w:300, h:20, x:28},   // low step left (abs y:330) — reachable from main floor at 372
                {y:150, w:500, h:20, x:200},   // cave ledge at abs y:250 — reachable from low step (80px gap)
                {y:70, w:280, h:20, x:580}     // upper cave perch right (abs y:170) — reachable from cave ledge (80px gap)
            ],
            doors: [
                {side:'left', offset:160, size:140},
                {side:'right', offset:160, size:140}
            ],
            features: [
                {type:'torch', x:100, y:110},
                {type:'roots', x:400, y:28, len:40},
                {type:'roots', x:600, y:28, len:50}
            ]},

        // ==============================
        // ROOM 8: Swamp Gate (6720-7680)
        // Boss room. Open arena, no right wall (exit).
        // One elevated platform.
        // ==============================
        {x:R8, y:60, w:960, h:340, theme:'village',
            noCeiling: false,
            floors: [
                {y:200, w:400, h:20, x:260} // center platform at abs y:260
            ],
            doors: [
                {side:'left', offset:200, size:140}
                // no right door — level exit (no right wall collision generated
                // because there's no door entry, but room still has right wall;
                // for open exit we keep a door that spans most of the wall)
            ],
            features: [
                {type:'torch', x:100, y:140},
                {type:'torch', x:800, y:140}
            ]}
    ],
    enemies: [
        // Room 1: Bandit guards (2) — main floor y:372, enemy y:320
        {type:'bandit', x:R1+350, y:320},
        {type:'bandit', x:R1+750, y:320},
        // Room 2: Drowner ground, bandit on 2nd floor (2)
        // main floor y:372 -> enemy 320; 2nd floor abs y:240 -> enemy 190
        {type:'drowner', x:R2+200, y:320},
        {type:'bandit', x:R2+400, y:190},
        // Room 3: Drowners on main floor (2) — y:320
        {type:'drowner', x:R3+300, y:320},
        {type:'drowner', x:R3+700, y:320},
        // Room 4: Bandits on each level (3)
        // main floor at y:20+380-28=372 -> enemy 320
        // mid floor abs y:240 -> enemy 190
        // choir loft abs y:140 -> enemy 90
        {type:'bandit', x:R4+200, y:320},
        {type:'bandit', x:R4+600, y:190},
        {type:'bandit', x:R4+450, y:90},
        // Room 5: Nekkers in cellar (4)
        // main floor at y:100+300-28=372 -> enemy 320
        {type:'nekker', x:R5+200, y:320},
        {type:'nekker', x:R5+400, y:320},
        {type:'nekker', x:R5+600, y:320},
        {type:'nekker', x:R5+800, y:320},
        // Room 6: Bandits in ruins (2) — main floor y:372 -> 320
        {type:'bandit', x:R6+200, y:320},
        {type:'bandit', x:R6+700, y:320},
        // Room 7: Nekkers in nest (4)
        // main floor at y:100+300-28=372 -> enemy 320
        {type:'nekker', x:R7+200, y:320},
        {type:'nekker', x:R7+400, y:320},
        {type:'nekker', x:R7+600, y:320},
        {type:'nekker', x:R7+800, y:320},
        // Room 8: Boss drowners (3) — main floor y:372 -> 320
        {type:'drowner', x:R8+300, y:320},
        {type:'drowner', x:R8+500, y:320},
        {type:'drowner', x:R8+700, y:320},
    ],
    spikes: [
        // Room 3: spikes at bottom of courtyard
        {x:R3+400, y:390, w:96, direction:'up'},
        // Room 7: spikes in nekker nest
        {x:R7+200, y:365, w:96, direction:'up'},
        {x:R7+550, y:365, w:96, direction:'up'},
    ],
    secrets: [
        // Room 4: secret in church choir loft
        {triggerX:R4+450, triggerY:130, reward:200,
         enemies:[{type:'nobleman', x:R4+470, y:90}, {type:'nobleman', x:R4+530, y:90}]},
    ],
    npcs: [
        {x: R1+500, y: 332, name: 'Alderman Yorick', lines: [
            'Witcher! Thank the gods you came. The nekkers have been worse than ever.',
            'We found this medallion on one of the dead ones. Strange markings... Nilfgaardian, maybe.',
            'The attacks started after witch hunters set up camp in the swamp to the east.',
            'Clear the village and take the medallion. Follow the trail to the swamp.'
        ]}
    ],
    endText: 'The medallion hums in Geralt\'s hand. Its magic is foreign — and dangerous.'
};


// ============================================================
// Level 2: The Swamp Depths - Room-based design
// 10 rooms, each ~960px wide. Swamp/cave theme.
// Collision generated by Room.generateCollision()
// ============================================================

var S1 = 0, S2 = 960, S3 = 1920, S4 = 2880, S5 = 3840, S6 = 4800;
var S7 = 5760, S8 = 6720, S9 = 7680, S10 = 8640;

W.StoryLevel2 = {
    name: 'The Swamp Depths',
    width: 9600,
    bgTheme: 'swamp',
    storyText: "The swamp hides witch hunters using cursed medallions to weaponize monsters...",
    platforms: [],
    rooms: [
        // ==============================
        // ROOM 1: Swamp Entrance - wooden hut (0-960)
        // y:60, h:340. Main floor at 372.
        // ==============================
        {x:S1, y:60, w:960, h:340, theme:'swamp',
            noCeiling: false,
            floors: [
                {y:200, w:500, h:20}        // shelf at abs y:260
            ],
            doors: [{side:'right', offset:200, size:140}],
            features: [
                {type:'torch', x:100, y:130},
                {type:'torch', x:800, y:130},
                {type:'roots', x:460, y:28, len:40}
            ]},

        // ==============================
        // ROOM 2: Hollow Tree - tall room (960-1920)
        // Tall: y:20, h:380. Two interior floors for climbing.
        // Main floor at 20+380-28=372. Mid floor at y:200 (abs 220). Upper at y:110 (abs 130).
        // ==============================
        {x:S2, y:20, w:960, h:380, theme:'swamp',
            noCeiling: true,
            floors: [
                {y:290, w:280, h:20, x:600},  // low branch right (abs y:310) — reachable from main floor at 372 (62px gap)
                {y:200, w:400, h:20, x:28},    // branch left (abs y:220) — reachable from low branch (90px gap)
                {y:200, w:400, h:20, x:500},   // branch right (abs y:220) — alternate path
                {y:110, w:600, h:20, x:160},   // canopy level at abs y:130 — reachable from branches (90px gap)
                {y:40, w:250, h:20, x:28}      // high canopy left (abs y:60) — reachable from canopy (70px gap)
            ],
            doors: [
                {side:'left', offset:240, size:140},
                {side:'right', offset:240, size:140}
            ],
            features: [
                {type:'torch', x:100, y:170},
                {type:'torch', x:800, y:170},
                {type:'roots', x:300, y:0, len:60},
                {type:'roots', x:600, y:0, len:50}
            ]},

        // ==============================
        // ROOM 3: Cave Tunnel 1 - low ceiling (1920-2880)
        // Cave: y:120, h:280. Main floor at 120+280-28=372.
        // One shelf floor inside.
        // ==============================
        {x:S3, y:120, w:960, h:280, theme:'swamp',
            noCeiling: false,
            floors: [
                {y:140, w:700, h:20}        // cave shelf at abs y:260
            ],
            doors: [
                {side:'left', offset:140, size:140},
                {side:'right', offset:140, size:140}
            ],
            features: [
                {type:'crystals', x:300, y:40},
                {type:'crystals', x:600, y:45},
                {type:'roots', x:460, y:28, len:30}
            ]},

        // ==============================
        // ROOM 4: Cave Tunnel 2 (2880-3840)
        // Cave: y:120, h:280. Main floor at 372.
        // ==============================
        {x:S4, y:120, w:960, h:280, theme:'swamp',
            noCeiling: false,
            floors: [
                {y:140, w:600, h:20, x:150} // cave shelf at abs y:260
            ],
            doors: [
                {side:'left', offset:140, size:140},
                {side:'right', offset:140, size:140}
            ],
            features: [
                {type:'crystals', x:200, y:40},
                {type:'roots', x:500, y:28, len:40},
                {type:'roots', x:700, y:28, len:35}
            ]},

        // ==============================
        // ROOM 5: Witch Hunter Camp 1 - stockade (3840-4800)
        // y:60, h:340. One upper walkway floor.
        // ==============================
        {x:S5, y:60, w:960, h:340, theme:'swamp',
            noCeiling: false,
            floors: [
                {y:180, w:904, h:20}        // walkway at abs y:240
            ],
            doors: [
                {side:'left', offset:200, size:140},
                {side:'right', offset:200, size:140}
            ],
            features: [
                {type:'torch', x:100, y:120},
                {type:'torch', x:800, y:120},
                {type:'banner', x:460, y:90, color:'#1a3a6a'}
            ]},

        // ==============================
        // ROOM 6: Witch Hunter Camp 2 - guard quarters (4800-5760)
        // y:60, h:340. One upper floor with gap for climbing.
        // ==============================
        {x:S6, y:60, w:960, h:340, theme:'swamp',
            noCeiling: false,
            floors: [
                {y:180, w:904, h:20}        // upper floor at abs y:240
            ],
            doors: [
                {side:'left', offset:200, size:140},
                {side:'right', offset:200, size:140}
            ],
            features: [
                {type:'torch', x:100, y:120},
                {type:'torch', x:800, y:120},
                {type:'chains', x:460, y:80, len:50}
            ]},

        // ==============================
        // ROOM 7: Prison Cell (5760-6720)
        // Tight: y:100, h:300. Main floor at 372. One shelf.
        // ==============================
        {x:S7, y:100, w:960, h:300, theme:'swamp',
            noCeiling: false,
            floors: [
                {y:160, w:600, h:20, x:150} // stone shelf at abs y:260
            ],
            doors: [
                {side:'left', offset:160, size:140},
                {side:'right', offset:160, size:140}
            ],
            features: [
                {type:'torch', x:100, y:110},
                {type:'chains', x:300, y:28, len:60},
                {type:'chains', x:600, y:28, len:55}
            ]},

        // ==============================
        // ROOM 8: Underground River (6720-7680)
        // y:60, h:340. One upper floor for traversal.
        // ==============================
        {x:S8, y:60, w:960, h:340, theme:'swamp',
            noCeiling: false,
            floors: [
                {y:180, w:800, h:20}        // upper floor at abs y:240
            ],
            doors: [
                {side:'left', offset:200, size:140},
                {side:'right', offset:200, size:140}
            ],
            features: [
                {type:'torch', x:100, y:130},
                {type:'torch', x:800, y:130},
                {type:'roots', x:460, y:28, len:40}
            ]},

        // ==============================
        // ROOM 9: Boss Cavern Entry (7680-8640)
        // Tall: y:40, h:360. Two interior floors for climbing.
        // Main floor at 40+360-28=372.
        // ==============================
        {x:S9, y:40, w:960, h:360, theme:'swamp',
            noCeiling: false,
            floors: [
                {y:210, w:904, h:20},       // mid floor at abs y:250
                {y:120, w:600, h:20, x:160} // upper floor at abs y:160
            ],
            doors: [
                {side:'left', offset:220, size:140},
                {side:'right', offset:220, size:140}
            ],
            features: [
                {type:'torch', x:100, y:160},
                {type:'torch', x:800, y:160},
                {type:'crystals', x:460, y:60}
            ]},

        // ==============================
        // ROOM 10: Boss Cavern - Witch Hunter Captain (8640-9600)
        // y:60, h:340. One elevated platform. No right wall (exit).
        // ==============================
        {x:S10, y:60, w:960, h:340, theme:'swamp',
            noCeiling: false,
            floors: [
                {y:200, w:500, h:20, x:210} // center platform at abs y:260
            ],
            doors: [
                {side:'left', offset:200, size:140}
                // no right door — level exit
            ],
            features: [
                {type:'torch', x:100, y:140},
                {type:'torch', x:800, y:140}
            ]}
    ],
    enemies: [
        // Room 1: Ghouls in hut (2) — main floor y:372 -> enemy 320
        {type:'ghoul', x:S1+300, y:320},
        {type:'ghoul', x:S1+700, y:320},
        // Room 2: Ghouls in tree (2) — main floor 320, canopy floor abs 130 -> enemy 80
        {type:'ghoul', x:S2+300, y:320},
        {type:'ghoul', x:S2+600, y:80},
        // Room 3: Ghouls in cave (3) — main floor y:372 -> 320
        {type:'ghoul', x:S3+200, y:320},
        {type:'ghoul', x:S3+500, y:320},
        {type:'ghoul', x:S3+800, y:320},
        // Room 4: Ghouls deeper (2) — main floor y:372 -> 320
        {type:'ghoul', x:S4+300, y:320},
        {type:'ghoul', x:S4+650, y:320},
        // Room 5: Witch hunters (3) — main floor 320, walkway abs 240 -> enemy 190
        {type:'witchHunter', x:S5+200, y:320},
        {type:'witchHunter', x:S5+500, y:320},
        {type:'witchHunter', x:S5+800, y:190},
        // Room 6: Witch hunters (3) — main floor 320, upper abs 240 -> enemy 190
        {type:'witchHunter', x:S6+200, y:320},
        {type:'witchHunter', x:S6+500, y:320},
        {type:'witchHunter', x:S6+750, y:190},
        // Room 7: Prison guards (2) — main floor y:372 -> 320
        {type:'witchHunter', x:S7+400, y:320},
        {type:'witchHunter', x:S7+700, y:320},
        // Room 8: Drowners (3) — main floor y:372 -> 320
        {type:'drowner', x:S8+200, y:320},
        {type:'drowner', x:S8+500, y:320},
        {type:'drowner', x:S8+800, y:320},
        // Room 9: Guards (2) — main floor y:372 -> 320
        {type:'witchHunter', x:S9+300, y:320},
        {type:'witchHunter', x:S9+700, y:320},
        // Room 10: Boss fight (3) — main floor y:372 -> 320
        {type:'witchHunter', x:S10+300, y:320},
        {type:'witchHunter', x:S10+600, y:320},
        {type:'ghoul', x:S10+450, y:320},
    ],
    spikes: [
        // Room 3: cave floor spikes
        {x:S3+400, y:365, w:96, direction:'up'},
        // Room 7: prison floor spikes
        {x:S7+450, y:365, w:72, direction:'up'},
        // Room 8: spike pits in underground river
        {x:S8+350, y:390, w:96, direction:'up'},
        {x:S8+650, y:390, w:96, direction:'up'},
    ],
    secrets: [
        // Room 9: hidden on upper floor
        {triggerX:S9+400, triggerY:150, reward:250,
         enemies:[{type:'wraith', x:S9+430, y:110}, {type:'ghoul', x:S9+550, y:110}]},
    ],
    npcs: [
        {x: S7+500, y: 332, name: 'Prisoner Annika', lines: [
            'You... you\'re a witcher? Please, get me out of these chains!',
            'The witch hunters — they\'re not just hunting mages. They\'re using cursed medallions to control the monsters.',
            'I overheard their captain. Nilfgaard is funding the whole operation. They have a fortress in the old keep.',
            'Take the documents from the captain\'s quarters. They prove everything.'
        ]}
    ],
    endText: 'Among the captain\'s papers, Geralt finds orders bearing the Nilfgaardian sun. The conspiracy runs deep.'
};

})();
